concinnity:
  outputs:
    dev:
      dataset: dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/merlynvillacorta/Documents/Concinnity/dbt.json
      location: US
      method: service-account
      priority: interactive
      project: concinnity
      threads: 4
      type: bigquery
    prod:
      dataset: prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/merlynvillacorta/Documents/Concinnity/dbt.json
      location: US
      method: service-account
      priority: interactive
      project: concinnity
      threads: 4
      type: bigquery
  target: dev
