name: DBT Build on PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '!main'

jobs:
  dbt_run_on_pr:
    runs-on: ubuntu-latest
    env:
      # dbt env variables used in your dbt profiles.yml
      DBT_PROFILES_DIR: ./
      DBT_GOOGLE_PROJECT: ${{ vars.DBT_GOOGLE_PROJECT }}
      DBT_GOOGLE_DATASET: ${{ vars.DBT_GOOGLE_DATASET }}
      
      # the contents of the keyfile pulled from GitHub Actions secrets 
      KEYFILE_CONTENTS: ${{secrets.KEYFILE_CONTENTS}}

    steps:
      - uses: "actions/checkout@main"

      - name: install requirements
        run: pip install -q -r requirements.txt

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.KEYFILE_CONTENTS }}" | base64 -d > /tmp/dbt_keyfile.json
          
      - name: dbt deps
        run: |
          dbt deps
        
      - name: dbt build
        run: |
          dbt build --target prod